# Generated by Django 4.1.3 on 2022-11-15 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(max_length=100)),
                ('Telefone', models.CharField(max_length=11)),
                ('Email', models.EmailField(max_length=254)),
                ('Foto', models.ImageField(upload_to='Media/Empresa')),
                ('Ativo', models.BooleanField(default=True)),
                ('Registro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(max_length=100)),
                ('Telefone', models.CharField(max_length=11)),
                ('Email', models.EmailField(max_length=254)),
                ('Foto', models.ImageField(upload_to='Media')),
                ('Ativo', models.BooleanField(default=True)),
                ('Registro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
