# Generated by Django 4.1.3 on 2022-11-16 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UNIMAR', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(max_length=100)),
                ('Telefone', models.CharField(max_length=13)),
                ('Email', models.EmailField(max_length=254)),
                ('Foto', models.ImageField(upload_to='Media')),
                ('Ativo', models.BooleanField(default=True)),
                ('Registro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Media',
        ),
        migrations.AlterField(
            model_name='empresa',
            name='Telefone',
            field=models.CharField(max_length=13),
        ),
    ]
